base:
  #  env: Dev or Test or Prod
  env: Dev

web:
  port: 8088

mongo:
  source: mongodb://127.0.0.1:27017/?maxPoolSize=20
  data_base: DBDashFun

telegram:
  token: ${telegram_bot_token}

log:
  path: ./logs/game_center.log

aws_pinpoint:
  key_id: ${aws_pinpoint_access_key_id}
  secret: ${aws_pinpoint_access_key}

admin_cfg:
  name: admin
  password: ${admin_password}
  # 后端数据查询使用的密码
  backend_password: ${admin_search_password}

tencent_cos:
  bucket_url: https://dashfun-1322633994.cos.accelerate.myqcloud.com
  service_url: https://cos.ap-singapore.myqcloud.com
  secret_id: ${tencent_cos_secret_id}
  secret_key: ${tencent_cos_secret_key}

