base:
  #  env: Dev or Test or Prod
  env: Dev

web:
  port: 8088

mongo:
  source: mongodb://127.0.0.1:27017/?maxPoolSize=20
  data_base: DBDashFun

telegram:
  token: ${telegram_bot_token}

log:
  path: ./logs/game_center.log

aws_pinpoint:
  key_id: ${aws_pinpoint_access_key_id}
  secret: ${aws_pinpoint_access_key}

admin_cfg:
  name: admin
  password: ${admin_password}